---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-volume-as-tacc-test
  labels:
    app: flask-cube-redis
    env: test
    username: astacc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi