---
apiVersion: v1
kind: Service
metadata:
  name: flask-cube-redis-flask-service
  labels:
    app: flask-cube-redis-flask-service
    env: test
    username: astacc
spec:
  type: ClusterIP
  selector:
    app: flask-cube-redis-flask
    name: flask-redis
    env: test
    username: astacc
  ports:
  - name: flask-cube-redis
    port: 5026
    targetPort: 5000