---
apiVersion: v1
kind: Service
metadata:
  name: flask-cube-redis-flask-service
  labels:
    app: flask-cube-redis-flask-service
    env: test
    username: astacc
spec:
  type: ClusterIP
  selector:
    app: flask-cube-redis-flask
    env: test
    username: astacc
  ports:
  - name: http
    port: 5000
    targetPort: 5026