---
apiVersion: v1
kind: Service
metadata:
  name: flask-cube-redis-service
  labels:
    app: flask-cube-redis-service
    env: test
    username: astacc
spec:
  type: ClusterIP
  selector:
    app: flask-cube-redis-redis
    env: test
    username: astacc
  ports:
  - name: flask-cube-redis
    port: 6426
    targetPort: 6379